---
title: "RNA-seq analysis and Shiny application"
author: "David GALLIEN & Gabin COUDRAY"
date: "15/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DESeq2)
library(Biobase)
library(gplots)
library(RColorBrewer)
library(shiny)
library(tidyverse)
library(NMF)
```

<p>&nbsp; </p> 
## Introduction
<p style="text-align:justify";>
Most of biological researchers does not have time to use the tools which allow to analyze the data generated by new technology. It is why it is imperative to offer to biologist facilitate tools that can allow them to be more efficient and conscenrate on there research.<p/>

<p style="text-align:justify";>
In our project we want to be able to generate application that can help them to explore there data and their results in R environment. For that, Shiny package allows to create interactive web applications.<p/>

<p style="text-align:justify";>
Nevertheless to create a vizualisation interactive application we need to have something to show. In medical research which is the main field we want to explore, next generation sequencing are often use and generate big data which we need to be analyzed and explored. We decided to concentrate our work on RNA sequencing (RNA-seq), this next generation sequencing had the purpose to detect differential express between cellular type of different condition.<p/>

## Objectives
### Context
<p style="text-align:justify";>
RNA-seq is a new way for sequencig RNA fastly than previous techniques like Sanger. The main aim of RNA-seq is the study of the differential expression of genes between different conditions. RNA sequencing was cited for the first time in 2008. Since, the number of publication with RNA-seq data grown exponentially. This kind of analysis uses NGS (Next-Generation Sequencing) technology like Illumina, Roche 454 or Ion torrent. 
</p>
An RNA sequencing analysis presents 3 main steps :  

 - Random fragmentation of mature RNA  
 
 - Amplification of fragments by PCR  
 
 - Sequencing of these amplified fragments making millions of reads
 
<p style="text-align:justify";>
The number of reads obtained is proportional to the abundance of RNA in the cell. These reads are stored in fastQ format files and their quality is estimated. Then each read is mapped to the genome of the organism. After the mapping we got BAM files in which every lines represent an alignment of a read. Finally, we count the number of reads by position and make a table in order to analyse this.
</p>

<p style="text-align:justify";>
Today more and more studies use RNA sequencing then there are more and more data to analyze. By following this problematic we will set up an Rshiny application allowing to analyze the RNA-seq data as deeply as possible. This application aims to answer as many questions as possible and visualize the results intuitively.
</p>

### Shiny application
<p style="text-align:justify";>
Shiny is an R package that permit to build easily dynamic and interactive web applications. An Rshiny application is separated into two parts :  

 - A User Interface (UI) which controls the appearance of the app  
 
 - A server function contains the build of the app  
</p>
<p style="text-align:justify";>
Our goal is to create an application which allows to visualize the data of an RNA-seq analysis. This application will take in input the count table obtained after the RNAseq, normalize the data and analyse it with statistical techniques. We want to display plots like MAplot, Volcano plot and others results from statistical analysis. All this to find a potential differential gene expression.
</p>
<p>&nbsp; </p> 
<p> First we will explain more deeply the RNA-seq analysis then we will proceed to the count table analysis under R thanks to the package DESeq2. Finally, we will create the Shiny app to study the results of the analysis. </p>

### RNA-sequencing data analysis
#### Step 1 : Data generation
<p style="text-align:justify";>
Firstly, to get the dataset, RNA is extraced from cells and mRNA are isolated by poly-A selection. Once extracted, mRNA are fragmented and reverse transcribed into cDNA. Then, cDNA are sequenced with adaptadors sequences using NGS technologies. The most used today is the Illumina technologie. This technologie uses clonal amplification and sequencing by synthesis (SBS). The sequencing can be "single end" (each read is independant) or "paired-end" (reads are paired). After the sequencing, millions of reads are produced.
</p>
#### Step 2 : Quality
<p style="text-align:justify";>
The sequencer gives as a result some FASTQ files. In this kind of file, a read is represented by a block of four lines. Then we can use a programm like FastQC to check the fiability of the sequencing.
</p>
#### Step 3 : Mapping
<p style="text-align:justify";>
This part of the analysis consists in aligning all the reads on the genome of the organism studied. One read is mapped to the region of the genome which is the most similar. The mean of the number of reads mapped on a region is called the depth. After the mapping, we get BAM files in which each line represent a read.
</p>
#### Step 4 : Quantification
<p style="text-align:justify";>
The number of reads is a reflection of the RNA abundance of RNA in the cell then we can estimate the expression level of the gene. That's why it is important to count the read mapped for each gene. The aim of this step is to build a count table in order to import it in R and manipulate easily.
</p>
#### Step 5 : Statistics
<p style="text-align:justify";>
We can visualize our data by a density signal on a genome browser like IGV. This allows to see the position of the exons and the level of expressions. We can also produce plot like MA-plot or Volcano plot in order to compare samples.
</p>
<p style="text-align:justify";>
To go further and see if there is a differential expression we have to normalize the data and then use differents statistical tests. We obtain adjusted p-value with which we can do a list of gene defirentially expressed.
</p>

### DESeq2
#### What is DESeq2 ?
<p style="text-align:justify";>
DESeq2 is package from R which means Differential gene expression analysis based on the negative binomial distribution. It is available on Bioconductor, a webside which provides open source software for bioinformatics and more specificly for the analysis and the study of high-throughput sequencing like RNA-seq here. With the differents tools of this packages, we can estimate some mean-variance relation in the data and test for differential expression based on a model using the negative binomial distribution. 
</p>
<p style="text-align:justify";>
The negative binomial distribution is an alternative to Poisson law. It is a discrete probability distribution. We consider an experiment which can give a success of probability p or a failure and this experiment continue until we obtain a given number of successes. The aim is to know the number of fails before the given number of successes.
</p>
<p style="text-align:justify";>
We use te negative binomial distribution because count read data is not a continuous thing so they only take non-negative integer values and we can't use a normal distribution. In the negative binomial distribution, the variance is always greater than the mean, or equal. Further, in RNA-seq, under-expressed genes have a greater variance thant overexpressed genes.
</p>

#### Dataset
<p style="text-align:justify";>
We will proceed to a differential gene expression analysis using DESeq2. To do this we have data from a study of Himes BE, Jiang X, Wagner P, et al. named RNA-Seq transcriptome profiling identifies CRISPLD2 as a glucocorticoid responsive gene that modulates cytokine function in airway smooth muscle cells. Glucocorticoid are used to treat asthma and the aim of this article is to understand the mechanism in the airway smooth muscle using RNA-seq.
</p>
<p style="text-align:justify";>
The experiment involve 8 samples, 4 treated samples with dexamethasone (synthetic glucocoricoid) and 4 control sample with no treatment. 
As a data we have a reads count table in which we can find the number of read mapped for each gene in each sample. We have also a metadata table in which we have informations for the 8 samples. And finally a gene annotation data in which we have informations about all the genes.
</p>





